### ISSUE TITLE
Supported OS in module?

### ISSUE THREAD

**Issue by TaylorMutch** [terraform-google-modules/terraform-google-forseti#135]
Is Debian the only supported distribution? The default image being used appears to be Ubuntu 18.04 rather than Debian, but the description of the variable seems to suggest otherwise - https://github.com/terraform-google-modules/terraform-google-forseti/blob/master/variables.tf#L73

**Comment by morgante** [comment]
I believe only Ubuntu is supported, #139 added to clarify.
