### ISSUE TITLE
Removing binding at service account creation

### ISSUE THREAD

**Issue by menendezjaume** [terraform-google-modules/terraform-google-forseti#21]
The setup helper (/helpers/setup.sh), in line 86 has a _remove iam policy binding_ for a newly created service account, which didn't have that policy in the first place, This causes the script to complain that the service account doesn't have the relevant permissions. I believe it should be replaced by an add like all the other bindings in the file:

```
86 gcloud projects remove-iam-policy-binding ${PROJECT_ID} \
87    --member="serviceAccount:${SERVICE_ACCOUNT_ID}" \
89    --role="roles/iam.serviceAccountUser" \
90    --user-output-enabled false
```

**Comment by adrienthebo** [comment]
Thanks for catching this, it looks like we resolved this typo in 31b12194c7b4153cb8f3ce7a422bd058381734cd. Since it looks like this issue was resolved I'm going to close out this issue; if this is still a problem please comment on this pull request and we can continue this conversation.
