### ISSUE TITLE
accScript.sh SED does not work with Mac

### ISSUE THREAD

**Issue by cleibl** [terraform-google-modules/terraform-google-forseti#24]
The accScript.sh uses the GNU version of sed.  If running this on a Mac, the apply will fail due to the default sed is a different (BSD) flavor.

A quick workaround is to install gsed using 'brew install gnu-sed' and updating the accScript to use the gsed command instead of sed

The README.md should be updated to reflect this

**Comment by adrienthebo** [comment]
The reference to `accScript.sh` was removed in the Forseti v1.0 release (f34744fa336e08836064b14073858773606a795c), this issue should be resolved. @cleibl could you try out the latest version of this module and see if your issue has been resolved?
