### ISSUE TITLE
Startup scripts failed to get executed on a fresh deployment

### ISSUE THREAD

**Issue by rx007** [terraform-google-modules/terraform-google-forseti#51]
# Startup scripts failed to get executed on a fresh deployment

Created a default terraform plan and all went well, 71 resources created, and no errors but when I login to the server/client, there's no forseti service nor forseti_security directory under /home/ubuntu or anywhere. Is this related to this bug? https://stackoverflow.com/questions/50422205/gce-startup-script-fails-to-run-on-ubuntu-18-04

```
module "forseti" {
  source  = "terraform-google-modules/forseti/google"
  version = "1.0.0"

  gsuite_admin_email = "me@mydomain.com"
  domain             = "mydomain.com"
  project_id         = "myproject"
  org_id             = "7777777777777"
}
```

### terraform output
```
...
module.forseti.client.google_compute_instance.forseti-client: Still creating... (10s elapsed)
module.forseti.client.google_compute_instance.forseti-client: Still creating... (20s elapsed)
module.forseti.module.client.google_compute_instance.forseti-client: Creation complete after 22s (ID: forseti-client-vm-xxxxx)

Apply complete! Resources: 71 added, 0 changed, 0 destroyed.
```

**Comment by adrienthebo** [comment]
I believe that you ran into the issue solved in https://github.com/terraform-google-modules/terraform-google-forseti/commit/89df50062e57e80be18fab93147f57ca5bd04a19, could you change your source to "github.com/terraform-google-modules/terraform-google-forseti?ref=e44d8b5" ? That's the latest commit on master and should address your issue.

**Comment by rx007** [comment]
@adrienthebo Thanks so much! That fixed it so closing this issue.

Cheers,

Rex
